void ssSetDigit(int digit);
void ssDisplayZero();
void ssDisplayOne();
void ssDisplayTwo();
void ssDisplayThree();
void ssDisplayFour();
void ssDisplayFive();
void ssDisplaySix();
void ssDisplaySeven();
void ssDisplayEight();
void ssDisplayNine();
void ssDisplay(int num);
